# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
文章:
- changed-files:
  - any-glob-to-any-file: src/posts/**
  
# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
# 新功能:
#  - head-branch: ['^feature', 'feat']

等待处理:
- changed-files:
  - any-glob-to-any-file: '**'

依赖更新:
 - head-branch: ['^renovate', 'renovate']